# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

WORKDIR /YOUR ROUTE TO MAP/Binance_Dust_To_BNB

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "main"]